### ISSUE TITLE
got an error with initialize.py

### ISSUE THREAD

**Issue by accidentalid** [mlpc-ucsd/Patch-DM#11]
Traceback (most recent call last):
  File "/home/ESSD1/JL/Patch-DM/initialize.py", line 29, in <module>
    model = Semantic(length, device='cuda', conf=conf, initial_clip=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ESSD1/JL/Patch-DM/model/blocks.py", line 589, in __init__
    data.transform = preprocess
    ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'transform'

Is there something wrong with my custom dataset?

**Comment by hongsheng-Z** [comment]
Hello, I had the same problem, did you solve it

**Comment by accidentalid** [comment]
> Hello, I had the same problem, did you solve it

 In the file dataset.py, I wrote my custom dataset class and use it in the make_dataset() method in the config.py file. This seems to solve the problem
