### ISSUE TITLE
training image size

### ISSUE THREAD

**Issue by oscarwooberry** [mlpc-ucsd/Patch-DM#6]
Thank you so much for sharing the amazing work! I have a question regarding training image resolution,  in img2lmdb.py I only see it converting size up to 1024. Do you support even higher resolutions such as 2k or 4k and patchify? My dataset mostly 3k resolution images. Thank you!

**Comment by Mq-Zhang1** [comment]
We didn't explore further above 1024. But yeah, the method theoretically practical for any resolution using the same method to patchify. And you may use a different base model architecture of 256or512 to improve the performance by reducing total patch numbers for higher resolutions.
